sudo: required
dist: trusty

branches:
  only:
    - master

language: python

python:
  - 3.5

env:
  - TOXENV=py35

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install tox
  # Get pyrrc5, lupdate etc ...
  - sudo apt-get install pyqt5-dev-tools

script:
  - tox

after_success:
  - coveralls
