branches:
  only:
    - master

language: python

python:
  - 3.5

env:
  - TOXENV=py35

install:
  - pip install -r requirements.txt
  - pip install python-qt5
  - pip install coveralls
  - pip install tox

script:
  - tox

after_success:
  - coveralls
