sudo: required
dist: trusty

branches:
  only:
    - master
    - rework

language: python

python:
  - 3.5

env:
  - TOXENV=py35

before_install:
  - sudo apt-get update -qq
  # Get pyrrc, lupdate etc ...
  - sudo apt-get install -y pyqt5-dev-tools

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install tox

script:
  - tox

after_success:
  - coveralls
